# Start the service with the command 'docker-compose up -d'

version: '3.9'

services:
  mongo-bch-dex:
    image: mongo:4.2.0
    container_name: mongo-bch-dex
    ports:
      - '5666:27017' # <host port>:<container port>
    volumes:
      - ../data/database:/data/db
    command: mongod --logpath=/dev/null # -- quiet
    restart: always

  ipfs:
    image: christroutner/trickle-ipfs-rpi:v1.0.1
    #image: odanado/go-ipfs:v0.11.0
    container_name: ipfs
    environment:
      IPFS_DAEMON_ARGUMENTS: '--enable-pubsub-experiment --migrate=true --agent-version-suffix=docker --routing=dhtclient'
      UPLOAD_KBPS: '25'
      DOWNLOAD_KBPS: '25'
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '10'
    mem_limit: 1000mb
    ports:
      - 4001:4001
      - 4003:4003
      - 172.17.0.1:5001:5001
      - 172.17.0.1:8080:8080
    volumes:
      - ./data/go-ipfs:/root/.ipfs
    command: [
      './start-ipfs.sh'
    ]
    restart: always

  p2wdb:
    #build:
    #  context: ./p2wdb/
    #  dockerfile: Dockerfile
    image: christroutner/p2wdb-rpi:v3.1.5
    container_name: p2wdb
    environment:
      CONSUMER_URL: 'https://wa-usa-bch-consumer.fullstackcash.nl'
      DEBUG_LEVEL: 1
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '10'
    mem_limit: 1gb
    links:
      - mongo-bch-dex
    ports:
      # <host port>:<container port>
      - 5667:5667 # REST API
      #- 5668:5668 # IPFS TCP port
      #- 5669:5669 # IPFS WS Port
    volumes:
      - ../data/ipfsdata/p2wdb:/home/safeuser/ipfs-p2wdb-service/.ipfsdata/p2wdb
      - ./p2wdb/start-production.sh:/home/safeuser/ipfs-p2wdb-service/start-production.sh
    restart: always

  bch-dex:
    #build:
    # context: ./bch-dex/
    # dockerfile: Dockerfile
    image: christroutner/bch-dex-rpi:v1.13.0
    container_name: bch-dex
    environment:
      #CONSUMER_URL: 'https://free-bch.fullstack.cash'
      CONSUMER_URL: 'https://wa-usa-bch-consumer.fullstackcash.nl'
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '10'
    mem_limit: 1000mb
    links:
      - mongo-bch-dex
      - p2wdb
    ports:
      - '5700:5700' # <host port>:<container port>
    volumes:
      - ../scripts/wallet.json:/home/safeuser/bch-dex/wallet.json
      - ./bch-dex/start-production.sh:/home/safeuser/bch-dex/start-production.sh
    restart: always

  dex-ui:
    #build:
    #  context: ./bch-dex-ui/
    #  dockerfile: Dockerfile
    image: christroutner/bch-dex-ui-rpi:v1.13.0
    container_name: dex-ui
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '10'
    mem_limit: 500mb
    links:
      - bch-dex
    ports:
      - '4500:80' # <host port>:<container port>
    # volumes:
    #   - ../data/ipfsdata:/home/safeuser/ipfs-service-provider/.ipfsdata
    restart: always
